spring.application.name=degitalslambook
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
project.image=uploads/images
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

supabase.url=${SUPABASE_URL}
supabase.service-key=${SUPABASE_SERVICE_KEY}
supabase.bucket=slam-book-files