spring.application.name=degitalslambook
spring.datasource.username=postgres
spring.datasource.password=vaibhao
spring.datasource.url=jdbc:postgresql://localhost:5432/degitalslambook
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true